In [66]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [54]:
deliveries  = pd.read_csv("deliveries_updated_ipl_upto_2025.csv")
matches = pd.read_csv("matches_updated_ipl_upto_2025.csv")
ball_by_ball = pd.read_csv("IPL_ball_by_ball_updated.csv")

In [14]:
ball_by_ball.shape

(278205, 20)

In [16]:
matches.shape

(1169, 28)

In [55]:
deliveries.shape

(278205, 20)

In [56]:
ball_by_ball.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14996 entries, 0 to 14995
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   match_id                14996 non-null  int64
 1   season                  14996 non-null  int64
 2   start_date              14996 non-null  object
 3   venue                   14996 non-null  object
 4   innings                 14995 non-null  float64
 5   ball                    14995 non-null  float64
 6   batting_team            14995 non-null  object
 7   bowling_team            14995 non-null  object
 8   striker                 14995 non-null  object
 9   non_striker             14995 non-null  object
 10  bowler                  14995 non-null  object
 11  runs_off_bat            14995 non-null  float64
 12  extras                  14995 non-null  float64
 13  wides                   505 non-null    float64
 14  noballs                 83 non-null     float64
 15  byes                    49 non-null     float64
 16  legbyes                 314 non-null    float64
 17  penalty                 1 non-null      float64
 18  wicket_type             780 non-null    object
 19  player_dismissed        780 non-null    object
 20  other_wicket_type       0 non-null      float64
 21  other_player_dismissed  0 non-null      float64
dtypes: float64(11), int64(2), object(9)
memory usage: 2.5+ MB

In [57]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 28 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   season           1169 non-null   object
 1   venue            1169 non-null   object
 2   event            1169 non-null   object
 3   winner_runs      531 non-null    float64
 4   umpire2          1169 non-null   object
 5   toss_winner      1169 non-null   object
 6   date             1169 non-null   object
 7   neutralvenue     77 non-null     object
 8   umpire1          1169 non-null   object
 9   city             1118 non-null   object
 10  reserve_umpire   1145 non-null   object
 11  winner           1146 non-null   object
 12  eliminator       15 non-null     object
 13  date1            2 non-null      object
 14  method           19 non-null     object
 15  team1            1169 non-null   object
 16  toss_decision    1169 non-null   object
 17  gender           1169 non-null   object
 18  team2            1169 non-null   object
 19  balls_per_over   1169 non-null   int64
 20  winner_wickets   615 non-null    float64
 21  tv_umpire        1165 non-null   object
 22  player_of_match  1161 non-null   object
 23  match_referee    1169 non-null   object
 24  outcome          23 non-null     object
 25  date2            2 non-null      object
 26  match_number     1099 non-null   float64
 27  matchId          1169 non-null   int64
dtypes: float64(3), int64(2), object(23)
memory usage: 255.8+ KB

In [58]:
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   matchId           278205 non-null  int64
 1   inning            278205 non-null  int64
 2   over_ball         278205 non-null  float64
 3   over              278205 non-null  int64
 4   ball              278205 non-null  int64
 5   batting_team      278205 non-null  object
 6   bowling_team      278205 non-null  object
 7   batsman           278205 non-null  object
 8   non_striker       278205 non-null  object
 9   bowler            278205 non-null  object
 10  batsman_runs      278205 non-null  int64
 11  extras            278205 non-null  int64
 12  isWide            9080 non-null    float64
 13  isNoBall          1163 non-null    float64
 14  Byes              701 non-null     float64
 15  LegByes           4215 non-null    float64
 16  Penalty           2 non-null       float64
 17  dismissal_kind    13823 non-null   object
 18  player_dismissed  13823 non-null   object
 19  date              278205 non-null  object
dtypes: float64(6), int64(6), object(8)
memory usage: 42.5+ MB

In [19]:
ball_by_ball.head()

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,extras,isWide,isNoBall,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date
0,335982,1,0.1,0,1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2008-04-18
1,335982,1,0.2,0,2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
2,335982,1,0.3,0,3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
3,335982,1,0.4,0,4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
4,335982,1,0.5,0,5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18

In [20]:
matches.head()

,season,venue,event,winner_runs,umpire2,toss_winner,date,neutralvenue,umpire1,city,...,team2,balls_per_over,winner_wickets,tv_umpire,player_of_match,match_referee,outcome,date2,match_number,matchId
0,2007/08,M Chinnaswamy Stadium,Indian Premier League,140.0,RE Koertzen,Royal Challengers Bangalore,2008-04-18,NaN,Asad Rauf,Bangalore,...,Kolkata Knight Riders,6,NaN,AM Saheba,BB McCullum,J Srinath,NaN,NaN,1.0,335982
1,2007/08,"Punjab Cricket Association Stadium, Mohali",Indian Premier League,33.0,SL Shastri,Chennai Super Kings,2008-04-19,NaN,MR Benson,Chandigarh,...,Chennai Super Kings,6,NaN,RB Tiffin,MEK Hussey,S Venkataraghavan,NaN,NaN,2.0,335983
2,2007/08,Feroz Shah Kotla,Indian Premier League,NaN,GA Pratapkumar,Rajasthan Royals,2008-04-19,NaN,Aleem Dar,Delhi,...,Rajasthan Royals,6,9.0,IL Howell,MF Maharoof,GR Viswanath,NaN,NaN,3.0,335984
3,2007/08,Eden Gardens,Indian Premier League,NaN,K Hariharan,Deccan Chargers,2008-04-20,NaN,BF Bowden,Kolkata,...,Deccan Chargers,6,5.0,Asad Rauf,DJ Hussey,FM Engineer,NaN,NaN,4.0,335986
4,2007/08,Wankhede Stadium,Indian Premier League,NaN,DJ Harper,Mumbai Indians,2008-04-20,NaN,SJ Davis,Mumbai,...,Royal Challengers Bangalore,6,5.0,AV Jayaprakash,MV Boucher,J Srinath,NaN,NaN,5.0,335985

In [59]:
deliveries.head()

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,extras,isWide,isNoBall,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date
0,335982,1,0.1,0,1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2008-04-18
1,335982,1,0.2,0,2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
2,335982,1,0.3,0,3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
3,335982,1,0.4,0,4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
4,335982,1,0.5,0,5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18

In [60]:
deliveries.isnull().sum()

matchId                  0
inning                   0
over_ball                0
over                     0
ball                     0
batting_team             0
bowling_team             0
batsman                  0
non_striker              0
bowler                   0
batsman_runs             0
extras                   0
isWide              269125
isNoBall            277042
Byes                277504
LegByes             273990
Penalty             278203
dismissal_kind      264382
player_dismissed    264382
date                     0
dtype: int64

In [21]:
ball_by_ball.isnull().sum()

matchId                  0
inning                   0
over_ball                0
over                     0
ball                     0
batting_team             0
bowling_team             0
batsman                  0
non_striker              0
bowler                   0
batsman_runs             0
extras                   0
isWide              269125
isNoBall            277042
Byes                277504
LegByes             273990
Penalty             278203
dismissal_kind      264382
player_dismissed    264382
date                     0
dtype: int64

In [22]:
matches.isnull().sum()

season                0
venue                 0
event                 0
winner_runs         638
umpire2               0
toss_winner           0
date                  0
neutralvenue       1092
umpire1               0
city                 51
reserve_umpire       24
winner               23
eliminator         1154
date1              1167
method             1150
team1                 0
toss_decision         0
gender                0
team2                 0
balls_per_over        0
winner_wickets      554
tv_umpire             4
player_of_match       8
match_referee         0
outcome            1146
date2              1167
match_number         70
matchId               0
dtype: int64

In [24]:
# Fill numeric missing values with 0
num_cols = ball_by_ball.select_dtypes(include='number').columns
ball_by_ball[num_cols] = ball_by_ball[num_cols].fillna(0)

# Fill categorical missing values
cat_cols = ball_by_ball.select_dtypes(include='object').columns
ball_by_ball[cat_cols] = ball_by_ball[cat_cols].fillna("Unknown")

In [62]:
num_cols = deliveries.select_dtypes(include='number').columns
deliveries[num_cols] = deliveries[num_cols].fillna(0)

cat_cols = deliveries.select_dtypes(include='object').columns
deliveries[cat_cols] = deliveries[cat_cols].fillna("Unknown")

In [25]:
matches = matches.fillna("Unknown")

In [63]:
def normalize_season(season):
    season = str(season)
    return int(season.split('/')[1]) if '/' in season else int(season)

matches['season'] = matches['season'].apply(normalize_season)

sorted(matches['season'].unique())

[np.int64(8),
 np.int64(10),
 np.int64(21),
 np.int64(2009),
 np.int64(2011),
 np.int64(2012),
 np.int64(2013),
 np.int64(2014),
 np.int64(2015),
 np.int64(2016),
 np.int64(2017),
 np.int64(2018),
 np.int64(2019),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024),
 np.int64(2025)]

In [30]:
ball_by_ball['total_runs'] = (
    ball_by_ball['batsman_runs'] + ball_by_ball['extras']
)

In [65]:
deliveries.drop_duplicates(inplace=True)
matches.drop_duplicates(inplace=True)
ball_by_ball.drop_duplicates(inplace=True)

In [31]:
ball_by_ball = ball_by_ball[
    ['matchId','batsman','bowler','batting_team','bowling_team',
     'total_runs']
]

In [33]:
matches = matches[['matchId','season','venue']]

In [35]:
player_match = (
    ball_by_ball.groupby(
        ['matchId','batsman','batting_team','bowling_team']
    )['total_runs']
    .sum()
    .reset_index()
)

In [37]:
player_match = player_match.merge(
    matches, on='matchId', how='left'
)

In [39]:
matches.groupby('season')['matchId'].count()

season
2007/08    58
2009       57
2009/10    60
2011       73
2012       74
2013       76
2014       60
2015       59
2016       60
2017       59
2018       60
2019       60
2020/21    60
2021       60
2022       74
2023       74
2024       71
2025       74
Name: matchId, dtype: int64

In [40]:
player_match.groupby('batsman')['total_runs'].sum() \
             .sort_values(ascending=False).head(10)

batsman
V Kohli           8993
RG Sharma         7320
S Dhawan          7119
DA Warner         6910
SK Raina          5780
MS Dhoni          5718
KL Rahul          5446
AB de Villiers    5354
CH Gayle          5336
AM Rahane         5257
Name: total_runs, dtype: int64

In [41]:
player_match.groupby('venue')['total_runs'].mean() \
             .sort_values(ascending=False).head(10)

venue
Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh    29.066667
Sawai Mansingh Stadium, Jaipur                                             26.271552
Punjab Cricket Association IS Bindra Stadium                               25.188406
Rajiv Gandhi International Stadium, Uppal, Hyderabad                       24.992727
Arun Jaitley Stadium, Delhi                                                24.957627
Eden Gardens, Kolkata                                                      24.474286
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh           24.421053
Himachal Pradesh Cricket Association Stadium, Dharamsala                   24.093023
Saurashtra Cricket Association Stadium                                     23.807143
Punjab Cricket Association IS Bindra Stadium, Mohali                       23.791946
Name: total_runs, dtype: float64

In [43]:
player_match = player_match.sort_values(['batsman','matchId'])

In [44]:
player_match['career_avg'] = (
    player_match.groupby('batsman')['total_runs']
    .expanding().mean()
    .reset_index(level=0, drop=True)
)

In [45]:
player_match['recent_form_5'] = (
    player_match.groupby('batsman')['total_runs']
    .rolling(5, min_periods=1).mean()
    .reset_index(level=0, drop=True)
)

In [46]:
player_match['opponent_avg'] = (
    player_match.groupby(['batsman','bowling_team'])['total_runs']
    .transform('mean')
)

In [47]:
player_match['venue_avg'] = (
    player_match.groupby(['batsman','venue'])['total_runs']
    .transform('mean')
)

In [48]:
final_df = player_match.dropna()

In [49]:
final_df.head()

,matchId,batsman,batting_team,bowling_team,total_runs,season,venue,career_avg,recent_form_5,opponent_avg,venue_avg
4299,548346,A Ashish Reddy,Deccan Chargers,Mumbai Indians,10,2012,Wankhede Stadium,10.000000,10.000000,13.500000,10.000000
4390,548352,A Ashish Reddy,Deccan Chargers,Chennai Super Kings,3,2012,"MA Chidambaram Stadium, Chepauk",6.500000,6.500000,15.000000,19.500000
4496,548359,A Ashish Reddy,Deccan Chargers,Kings XI Punjab,12,2012,"Rajiv Gandhi International Stadium, Uppal",8.333333,8.333333,13.666667,9.090909
4699,548373,A Ashish Reddy,Deccan Chargers,Rajasthan Royals,10,2012,"Rajiv Gandhi International Stadium, Uppal",8.750000,8.750000,12.666667,9.090909
4747,548376,A Ashish Reddy,Deccan Chargers,Royal Challengers Bangalore,5,2012,"Rajiv Gandhi International Stadium, Uppal",8.000000,8.000000,11.200000,9.090909

In [50]:
final_df.to_csv("final_ipl_player_dataset.csv", index=False)

In [52]:
import pandas as pd

# Load the CSV file into a DataFrame
final_df = pd.read_csv('final_ipl_player_dataset.csv')

# Convert the DataFrame to a string representation
txt_content = final_df.to_string()

# Save the string content to a .txt file
with open('final_ipl_player_dataset.txt', 'w') as f:
    f.write(txt_content)

print("'final_ipl_player_dataset.txt' created successfully.")

'final_ipl_player_dataset.txt' created successfully.

In [53]:
from google.colab import files

files.download('final_ipl_player_dataset.txt')

In [51]:
from google.colab import files

files.download('final_ipl_player_dataset.csv')

In [11]:
ball_by_ball = pd.read_csv('IPL_ball_by_ball_updated.csv')
matches = pd.read_csv('matches_updated_ipl_upto_2025.csv')

print("DataFrames loaded successfully: ball_by_ball, matches")

display(ball_by_ball.head())
display(matches.head())

DataFrames loaded successfully: ball_by_ball, matches

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,...,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,season,venue,event,winner_runs,umpire2,toss_winner,date,neutralvenue,umpire1,city,...,team2,balls_per_over,winner_wickets,tv_umpire,player_of_match,match_referee,outcome,date2,match_number,matchId
0,2007/08,M Chinnaswamy Stadium,Indian Premier League,140.0,RE Koertzen,Royal Challengers Bangalore,2008-04-18,NaN,Asad Rauf,Bangalore,...,Kolkata Knight Riders,6,NaN,AM Saheba,BB McCullum,J Srinath,NaN,NaN,1.0,335982
1,2007/08,"Punjab Cricket Association Stadium, Mohali",Indian Premier League,33.0,SL Shastri,Chennai Super Kings,2008-04-19,NaN,MR Benson,Chandigarh,...,Chennai Super Kings,6,NaN,RB Tiffin,MEK Hussey,S Venkataraghavan,NaN,NaN,2.0,335983
2,2007/08,Feroz Shah Kotla,Indian Premier League,NaN,GA Pratapkumar,Rajasthan Royals,2008-04-19,NaN,Aleem Dar,Delhi,...,Rajasthan Royals,6,9.0,IL Howell,MF Maharoof,GR Viswanath,NaN,NaN,3.0,335984
3,2007/08,Eden Gardens,Indian Premier League,NaN,K Hariharan,Deccan Chargers,2008-04-20,NaN,BF Bowden,Kolkata,...,Deccan Chargers,6,5.0,Asad Rauf,DJ Hussey,FM Engineer,NaN,NaN,4.0,335986
4,2007/08,Wankhede Stadium,Indian Premier League,NaN,DJ Harper,Mumbai Indians,2008-04-20,NaN,SJ Davis,Mumbai,...,Royal Challengers Bangalore,6,5.0,AV Jayaprakash,MV Boucher,J Srinath,NaN,NaN,5.0,335985