In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/IPL.csv")
df.head()
df.info()
df.describe()

/tmp/ipython-input-3456472252.py:3: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/drive/MyDrive/IPL.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 64 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         278205 non-null  int64
 1   match_id           278205 non-null  int64
 2   date               278205 non-null  object
 3   match_type         278205 non-null  object
 4   event_name         278205 non-null  object
 5   innings            278205 non-null  int64
 6   batting_team       278205 non-null  object
 7   bowling_team       278205 non-null  object
 8   over               278205 non-null  int64
 9   ball               278205 non-null  int64
 10  ball_no            278205 non-null  float64
 11  batter             278205 non-null  object
 12  bat_pos            278205 non-null  int64
 13  runs_batter        278205 non-null  int64
 14  balls_faced        278205 non-null  int64
 15  bowler             278205 non-null  object
 16  valid_ball         278205 non-null  int64
 17  runs_extras        278205 non-null  int64
 18  runs_total         278205 non-null  int64
 19  runs_bowler        278205 non-null  int64
 20  runs_not_boundary  278205 non-null  bool
 21  extra_type         15133 non-null   object
 22  non_striker        278205 non-null  object
 23  non_striker_pos    278205 non-null  int64
 24  wicket_kind        13823 non-null   object
 25  player_out         13823 non-null   object
 26  fielders           10013 non-null   object
 27  runs_target        133903 non-null  float64
 28  review_batter      872 non-null     object
 29  team_reviewed      872 non-null     object
 30  review_decision    872 non-null     object
 31  umpire             872 non-null     object
 32  umpires_call       278205 non-null  bool
 33  player_of_match    278205 non-null  object
 34  match_won_by       278205 non-null  object
 35  win_outcome        273503 non-null  object
 36  toss_winner        278205 non-null  object
 37  toss_decision      278205 non-null  object
 38  venue              278205 non-null  object
 39  city               278205 non-null  object
 40  day                278205 non-null  int64
 41  month              278205 non-null  int64
 42  year               278205 non-null  int64
 43  season             278205 non-null  object
 44  gender             278205 non-null  object
 45  team_type          278205 non-null  object
 46  superover_winner   3896 non-null    object
 47  result_type        4702 non-null    object
 48  method             3890 non-null    object
 49  balls_per_over     278205 non-null  int64
 50  overs              278205 non-null  int64
 51  event_match_no     278205 non-null  object
 52  stage              278205 non-null  object
 53  match_number       278205 non-null  object
 54  team_runs          278205 non-null  int64
 55  team_balls         278205 non-null  int64
 56  team_wicket        278205 non-null  int64
 57  new_batter         13321 non-null   object
 58  batter_runs        278205 non-null  int64
 59  batter_balls       278205 non-null  int64
 60  bowler_wicket      278205 non-null  int64
 61  batting_partners   278205 non-null  object
 62  next_batter        13321 non-null   object
 63  striker_out        278205 non-null  bool
dtypes: bool(3), float64(2), int64(24), object(35)
memory usage: 130.3+ MB

,Unnamed: 0,match_id,innings,over,ball,ball_no,bat_pos,runs_batter,balls_faced,valid_ball,...,month,year,balls_per_over,overs,team_runs,team_balls,team_wicket,batter_runs,batter_balls,bowler_wicket
count,278205.000000,2.782050e+05,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,...,278205.000000,278205.000000,278205.0,278205.0,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000
mean,139102.000000,9.422687e+05,1.482914,9.193839,3.488855,9.542725,3.612555,1.277378,0.967362,0.963182,...,4.787933,2016.710178,6.0,20.0,77.110498,58.614637,2.456972,18.327424,14.011211,0.045470
std,80311.010157,3.817198e+05,0.502571,5.681511,1.708263,5.682938,2.168978,1.651107,0.177687,0.188315,...,1.586724,5.248572,0.0,0.0,49.957873,34.117619,2.100374,18.578093,11.833930,0.208333
min,0.000000,3.359820e+05,1.000000,0.000000,1.000000,0.100000,1.000000,0.000000,0.000000,0.000000,...,3.000000,2008.000000,6.0,20.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,69551.000000,5.483530e+05,1.000000,4.000000,2.000000,4.500000,2.000000,0.000000,1.000000,1.000000,...,4.000000,2012.000000,6.0,20.0,36.000000,29.000000,1.000000,4.000000,5.000000,0.000000
50%,139102.000000,1.082601e+06,1.000000,9.000000,3.000000,9.400000,3.000000,1.000000,1.000000,1.000000,...,4.000000,2017.000000,6.0,20.0,73.000000,58.000000,2.000000,12.000000,11.000000,0.000000
75%,208653.000000,1.304049e+06,2.000000,14.000000,5.000000,14.400000,5.000000,1.000000,1.000000,1.000000,...,5.000000,2022.000000,6.0,20.0,113.000000,88.000000,4.000000,27.000000,20.000000,0.000000
max,278204.000000,1.485779e+06,6.000000,19.000000,7.000000,19.600000,11.000000,6.000000,1.000000,1.000000,...,11.000000,2025.000000,6.0,20.0,287.000000,121.000000,10.000000,175.000000,73.000000,1.000000

In [4]:
df.duplicated().sum()
df = df.drop_duplicates()

In [12]:
list(df.columns)

['Unnamed: 0',
 'match_id',
 'date',
 'match_type',
 'event_name',
 'innings',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'ball_no',
 'batter',
 'bat_pos',
 'runs_batter',
 'balls_faced',
 'bowler',
 'valid_ball',
 'runs_extras',
 'runs_total',
 'runs_bowler',
 'runs_not_boundary',
 'extra_type',
 'non_striker',
 'non_striker_pos',
 'wicket_kind',
 'player_out',
 'fielders',
 'runs_target',
 'review_batter',
 'team_reviewed',
 'review_decision',
 'umpire',
 'umpires_call',
 'player_of_match',
 'match_won_by',
 'win_outcome',
 'toss_winner',
 'toss_decision',
 'venue',
 'city',
 'day',
 'month',
 'year',
 'season',
 'gender',
 'team_type',
 'superover_winner',
 'result_type',
 'method',
 'balls_per_over',
 'overs',
 'event_match_no',
 'stage',
 'match_number',
 'team_runs',
 'team_balls',
 'team_wicket',
 'new_batter',
 'batter_runs',
 'batter_balls',
 'bowler_wicket',
 'batting_partners',
 'next_batter',
 'striker_out']

In [10]:
df['next_batter'] = df['next_batter'].fillna("None")

In [9]:
df.isnull().sum()

Unnamed: 0          0
match_id            0
date                0
match_type          0
event_name          0
                   ..
batter_balls        0
bowler_wicket       0
batting_partners    0
next_batter         0
striker_out         0
Length: 64, dtype: int64

In [15]:
df.dtypes

Unnamed: 0                   int64
match_id                     int64
date                datetime64[ns]
match_type                  object
event_name                  object
                         ...
batter_balls                 int64
bowler_wicket                int64
batting_partners            object
next_batter                 object
striker_out                   bool
Length: 64, dtype: object

In [16]:
df['date'] = pd.to_datetime(df['date'])

In [17]:
int_cols = [
    'innings', 'over', 'ball', 'ball_no',
    'bat_pos', 'balls_faced', 'runs_batter',
    'runs_extras', 'runs_total', 'runs_bowler',
    'runs_not_boundary', 'team_runs', 'team_balls',
    'team_wicket', 'balls_per_over', 'overs',
    'batter_runs', 'batter_balls', 'bowler_wicket'
]

df[int_cols] = df[int_cols].astype(int)

In [18]:
cat_cols = [
    'match_type', 'batting_team', 'bowling_team',
    'batter', 'bowler', 'non_striker', 'venue',
    'city', 'season', 'gender', 'team_type', 'wicket_kind',
    'player_out', 'fielders', 'extra_type'
]

df[cat_cols] = df[cat_cols].astype('category')

In [19]:
bool_cols = ['valid_ball', 'striker_out']
df[bool_cols] = df[bool_cols].astype('int8')

In [31]:
df.dtypes

match_id                      int64
date                 datetime64[ns]
match_type                 category
event_name                   object
innings                     float64
batting_team               category
bowling_team               category
over                          int64
ball                          int64
ball_no                       int64
batter                     category
bat_pos                     float64
runs_batter                 float64
balls_faced                   int64
bowler                     category
valid_ball                     int8
runs_extras                   int64
runs_total                  float64
runs_bowler                 float64
runs_not_boundary             int64
extra_type                 category
non_striker                category
non_striker_pos               int64
wicket_kind                category
player_out                 category
fielders                   category
runs_target                 float64
review_batter                object
team_reviewed                object
review_decision              object
umpire                       object
umpires_call                   bool
player_of_match              object
match_won_by                 object
win_outcome                  object
toss_winner                  object
toss_decision                object
venue                      category
city                       category
day                           int64
month                         int64
year                          int64
season                     category
gender                     category
team_type                  category
superover_winner             object
result_type                  object
method                       object
balls_per_over                int64
overs                         int64
stage                        object
match_number                 object
team_runs                   float64
team_balls                    int64
team_wicket                 float64
batter_runs                 float64
batter_balls                float64
bowler_wicket                 int64
dtype: object

In [33]:
num_cols = [
    'innings', 'over', 'ball', 'ball_no', 'bat_pos',
    'balls_faced', 'runs_batter', 'runs_extras',
    'runs_total', 'runs_bowler', 'runs_not_boundary',
    'team_runs', 'team_balls', 'team_wicket',
    'balls_per_over', 'overs', 'batter_runs', 'batter_balls', 'bowler_wicket'
]

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR

    # Cap outliers to limits (Winsorizing)
    df[col] = df[col].clip(lower, upper)

In [37]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 58 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           278205 non-null  int64
 1   date               278205 non-null  datetime64[ns]
 2   match_type         278205 non-null  category
 3   event_name         278205 non-null  object
 4   innings            278205 non-null  float64
 5   batting_team       278205 non-null  category
 6   bowling_team       278205 non-null  category
 7   over               278205 non-null  int64
 8   ball               278205 non-null  int64
 9   ball_no            278205 non-null  int64
 10  batter             278205 non-null  category
 11  bat_pos            278205 non-null  float64
 12  runs_batter        278205 non-null  float64
 13  balls_faced        278205 non-null  int64
 14  bowler             278205 non-null  category
 15  valid_ball         278205 non-null  int8
 16  runs_extras        278205 non-null  int64
 17  runs_total         278205 non-null  float64
 18  runs_bowler        278205 non-null  float64
 19  runs_not_boundary  278205 non-null  int64
 20  extra_type         15133 non-null   category
 21  non_striker        278205 non-null  category
 22  non_striker_pos    278205 non-null  int64
 23  wicket_kind        13823 non-null   category
 24  player_out         13823 non-null   category
 25  fielders           10013 non-null   category
 26  runs_target        133903 non-null  float64
 27  review_batter      872 non-null     object
 28  team_reviewed      872 non-null     object
 29  review_decision    872 non-null     object
 30  umpire             872 non-null     object
 31  umpires_call       278205 non-null  bool
 32  player_of_match    278205 non-null  object
 33  match_won_by       278205 non-null  object
 34  win_outcome        273503 non-null  object
 35  toss_winner        278205 non-null  object
 36  toss_decision      278205 non-null  object
 37  venue              278205 non-null  category
 38  city               278205 non-null  category
 39  day                278205 non-null  int64
 40  month              278205 non-null  int64
 41  year               278205 non-null  int64
 42  season             278205 non-null  category
 43  gender             278205 non-null  category
 44  team_type          278205 non-null  category
 45  superover_winner   3896 non-null    object
 46  result_type        4702 non-null    object
 47  method             3890 non-null    object
 48  balls_per_over     278205 non-null  int64
 49  overs              278205 non-null  int64
 50  stage              278205 non-null  object
 51  match_number       278205 non-null  object
 52  team_runs          278205 non-null  float64
 53  team_balls         278205 non-null  int64
 54  team_wicket        278205 non-null  float64
 55  batter_runs        278205 non-null  float64
 56  batter_balls       278205 non-null  float64
 57  bowler_wicket      278205 non-null  int64
dtypes: bool(1), category(15), datetime64[ns](1), float64(10), int64(15), int8(1), object(15)
memory usage: 93.0+ MB

,match_id,date,innings,over,ball,ball_no,bat_pos,runs_batter,balls_faced,valid_ball,...,month,year,balls_per_over,overs,team_runs,team_balls,team_wicket,batter_runs,batter_balls,bowler_wicket
count,2.782050e+05,278205,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.0,278205.000000,...,278205.000000,278205.000000,278205.0,278205.0,278205.000000,278205.000000,278205.000000,278205.000000,278205.000000,278205.0
mean,9.422687e+05,2017-01-23 17:45:07.831994368,1.482698,9.193839,3.488855,9.193839,3.602944,0.921605,1.0,0.963182,...,4.787933,2016.710178,6.0,20.0,77.090414,58.614637,2.451631,17.809279,13.818984,0.0
min,3.359820e+05,2008-04-18 00:00:00,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.0,0.000000,...,3.000000,2008.000000,6.0,20.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,5.483530e+05,2012-05-05 00:00:00,1.000000,4.000000,2.000000,4.000000,2.000000,0.000000,1.0,1.000000,...,4.000000,2012.000000,6.0,20.0,36.000000,29.000000,1.000000,4.000000,5.000000,0.0
50%,1.082601e+06,2017-04-13 00:00:00,1.000000,9.000000,3.000000,9.000000,3.000000,1.000000,1.0,1.000000,...,4.000000,2017.000000,6.0,20.0,73.000000,58.000000,2.000000,12.000000,11.000000,0.0
75%,1.304049e+06,2022-03-27 00:00:00,2.000000,14.000000,5.000000,14.000000,5.000000,1.000000,1.0,1.000000,...,5.000000,2022.000000,6.0,20.0,113.000000,88.000000,4.000000,27.000000,20.000000,0.0
max,1.485779e+06,2025-06-03 00:00:00,3.500000,19.000000,7.000000,19.000000,9.500000,2.500000,1.0,1.000000,...,11.000000,2025.000000,6.0,20.0,228.500000,121.000000,8.500000,61.500000,42.500000,0.0
std,3.817198e+05,NaN,0.501482,5.681511,1.708263,5.681511,2.140333,0.914153,0.0,0.188315,...,1.586724,5.248572,0.0,0.0,49.891349,34.117619,2.084034,16.919051,11.271575,0.0