In [24]:
import pandas as pd
import numpy as np

# Loading raw IPL ball-by-ball dataset
df = pd.read_csv("data/deliveries_initial.csv")

# Inspecting structure and data types
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   matchId           260920 non-null  int64
 1   inning            260920 non-null  int64
 2   over_ball         260920 non-null  float64
 3   over              260920 non-null  int64
 4   ball              260920 non-null  int64
 5   batting_team      260920 non-null  object
 6   bowling_team      260920 non-null  object
 7   batsman           260920 non-null  object
 8   non_striker       260920 non-null  object
 9   bowler            260920 non-null  object
 10  batsman_runs      260920 non-null  int64
 11  extras            260920 non-null  int64
 12  isWide            8381 non-null    float64
 13  isNoBall          1093 non-null    float64
 14  Byes              673 non-null     float64
 15  LegByes           4001 non-null    float64
 16  Penalty           2 non-null       float64
 17  dismissal_kind    12950 non-null   object
 18  player_dismissed  12950 non-null   object
 19  date              260920 non-null  object
dtypes: float64(6), int64(6), object(8)
memory usage: 39.8+ MB

,matchId,inning,over_ball,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,extras,isWide,isNoBall,Byes,LegByes,Penalty,dismissal_kind,player_dismissed,date
0,335982,1,0.1,0,1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,P Kumar,0,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2008-04-18
1,335982,1,0.2,0,2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
2,335982,1,0.3,0,3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
3,335982,1,0.4,0,4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18
4,335982,1,0.5,0,5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,P Kumar,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-18

In [25]:
# Standardizing column names to snake_case and lowercase
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
)

df.columns
# Dropping redundant over_ball column
if "over_ball" in df.columns:
    df = df.drop(columns=["over_ball"])
# Normalizing text-based columns
text_cols = [
    "batting_team", "bowling_team",
    "batsman", "non_striker", "bowler",
    "dismissal_kind", "player_dismissed"
]

for col in text_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.lower()
    )
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   matchid           260920 non-null  int64
 1   inning            260920 non-null  int64
 2   over              260920 non-null  int64
 3   ball              260920 non-null  int64
 4   batting_team      260920 non-null  object
 5   bowling_team      260920 non-null  object
 6   batsman           260920 non-null  object
 7   non_striker       260920 non-null  object
 8   bowler            260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extras            260920 non-null  int64
 11  iswide            8381 non-null    float64
 12  isnoball          1093 non-null    float64
 13  byes              673 non-null     float64
 14  legbyes           4001 non-null    float64
 15  penalty           2 non-null       float64
 16  dismissal_kind    260920 non-null  object
 17  player_dismissed  260920 non-null  object
 18  date              260920 non-null  object
dtypes: float64(5), int64(6), object(8)
memory usage: 37.8+ MB

,matchid,inning,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,extras,iswide,isnoball,byes,legbyes,penalty,dismissal_kind,player_dismissed,date
0,335982,1,0,1,kolkata knight riders,royal challengers bangalore,sc ganguly,bb mccullum,p kumar,0,1,NaN,NaN,NaN,1.0,NaN,nan,nan,2008-04-18
1,335982,1,0,2,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,0,NaN,NaN,NaN,NaN,NaN,nan,nan,2008-04-18
2,335982,1,0,3,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,1,1.0,NaN,NaN,NaN,NaN,nan,nan,2008-04-18
3,335982,1,0,4,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,0,NaN,NaN,NaN,NaN,NaN,nan,nan,2008-04-18
4,335982,1,0,5,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,0,NaN,NaN,NaN,NaN,NaN,nan,nan,2008-04-18

In [26]:
# Mapping old team names to current franchise names
team_name_map = {
    "delhi daredevils": "delhi capitals",
    "deccan chargers": "sunrisers hyderabad",
    "kings xi punjab": "punjab kings",
    "rising pune supergiant": "rising pune supergiants",
    "rising pune supergiants": "rising pune supergiants",
    "pune warriors": "defunct_pune_warriors",
    "gujarat lions": "defunct_gujarat_lions",
    "kochi tuskers kerala": "defunct_kochi_tuskers"
}

df["batting_team"] = df["batting_team"].replace(team_name_map)
df["bowling_team"] = df["bowling_team"].replace(team_name_map)
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   matchid           260920 non-null  int64
 1   inning            260920 non-null  int64
 2   over              260920 non-null  int64
 3   ball              260920 non-null  int64
 4   batting_team      260920 non-null  object
 5   bowling_team      260920 non-null  object
 6   batsman           260920 non-null  object
 7   non_striker       260920 non-null  object
 8   bowler            260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extras            260920 non-null  int64
 11  iswide            8381 non-null    float64
 12  isnoball          1093 non-null    float64
 13  byes              673 non-null     float64
 14  legbyes           4001 non-null    float64
 15  penalty           2 non-null       float64
 16  dismissal_kind    260920 non-null  object
 17  player_dismissed  260920 non-null  object
 18  date              260920 non-null  object
dtypes: float64(5), int64(6), object(8)
memory usage: 37.8+ MB

,matchid,inning,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,extras,iswide,isnoball,byes,legbyes,penalty,dismissal_kind,player_dismissed,date
0,335982,1,0,1,kolkata knight riders,royal challengers bangalore,sc ganguly,bb mccullum,p kumar,0,1,NaN,NaN,NaN,1.0,NaN,nan,nan,2008-04-18
1,335982,1,0,2,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,0,NaN,NaN,NaN,NaN,NaN,nan,nan,2008-04-18
2,335982,1,0,3,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,1,1.0,NaN,NaN,NaN,NaN,nan,nan,2008-04-18
3,335982,1,0,4,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,0,NaN,NaN,NaN,NaN,NaN,nan,nan,2008-04-18
4,335982,1,0,5,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,0,NaN,NaN,NaN,NaN,NaN,nan,nan,2008-04-18

In [27]:
# Replacing NaNs in delivery-level boolean/numeric extras
extras_cols = ["iswide", "isnoball", "byes", "legbyes", "penalty"]
df[extras_cols] = df[extras_cols].fillna(0)

# Handling missing dismissal information explicitly
df["dismissal_kind"] = df["dismissal_kind"].replace("nan", "none")
df["player_dismissed"] = df["player_dismissed"].replace("nan", "none")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   matchid           260920 non-null  int64
 1   inning            260920 non-null  int64
 2   over              260920 non-null  int64
 3   ball              260920 non-null  int64
 4   batting_team      260920 non-null  object
 5   bowling_team      260920 non-null  object
 6   batsman           260920 non-null  object
 7   non_striker       260920 non-null  object
 8   bowler            260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extras            260920 non-null  int64
 11  iswide            260920 non-null  float64
 12  isnoball          260920 non-null  float64
 13  byes              260920 non-null  float64
 14  legbyes           260920 non-null  float64
 15  penalty           260920 non-null  float64
 16  dismissal_kind    260920 non-null  object
 17  player_dismissed  260920 non-null  object
 18  date              260920 non-null  object
dtypes: float64(5), int64(6), object(8)
memory usage: 37.8+ MB

,matchid,inning,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,extras,iswide,isnoball,byes,legbyes,penalty,dismissal_kind,player_dismissed,date
0,335982,1,0,1,kolkata knight riders,royal challengers bangalore,sc ganguly,bb mccullum,p kumar,0,1,0.0,0.0,0.0,1.0,0.0,none,none,2008-04-18
1,335982,1,0,2,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,0,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18
2,335982,1,0,3,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,1,1.0,0.0,0.0,0.0,0.0,none,none,2008-04-18
3,335982,1,0,4,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,0,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18
4,335982,1,0,5,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,0,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18

In [28]:
# Computing total runs conceded on the delivery
df["total_runs"] = (
    df["batsman_runs"]
    + df["extras"]
    + df["byes"]
    + df["legbyes"]
    + df["penalty"]
)

# Creating striker-specific wicket indicator
df["is_wicket"] = np.where(
    (df["player_dismissed"] != "none") &
    (df["player_dismissed"] == df["batsman"]),
    1,
    0
)
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   matchid           260920 non-null  int64
 1   inning            260920 non-null  int64
 2   over              260920 non-null  int64
 3   ball              260920 non-null  int64
 4   batting_team      260920 non-null  object
 5   bowling_team      260920 non-null  object
 6   batsman           260920 non-null  object
 7   non_striker       260920 non-null  object
 8   bowler            260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extras            260920 non-null  int64
 11  iswide            260920 non-null  float64
 12  isnoball          260920 non-null  float64
 13  byes              260920 non-null  float64
 14  legbyes           260920 non-null  float64
 15  penalty           260920 non-null  float64
 16  dismissal_kind    260920 non-null  object
 17  player_dismissed  260920 non-null  object
 18  date              260920 non-null  object
 19  total_runs        260920 non-null  float64
 20  is_wicket         260920 non-null  int64
dtypes: float64(6), int64(7), object(8)
memory usage: 41.8+ MB

,matchid,inning,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,...,iswide,isnoball,byes,legbyes,penalty,dismissal_kind,player_dismissed,date,total_runs,is_wicket
0,335982,1,0,1,kolkata knight riders,royal challengers bangalore,sc ganguly,bb mccullum,p kumar,0,...,0.0,0.0,0.0,1.0,0.0,none,none,2008-04-18,2.0,0
1,335982,1,0,2,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,0.0,0
2,335982,1,0,3,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,1.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,1.0,0
3,335982,1,0,4,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,0.0,0
4,335982,1,0,5,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,0.0,0

In [29]:
# Removing logically invalid deliveries
df = df[df["inning"].isin([1, 2])]
df = df[df["over"].between(0, 20)]
df = df[df["ball"].between(1, 6)]
df = df[df["batsman_runs"] >= 0]
df = df[df["total_runs"] >= 0]
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 251456 entries, 0 to 260919
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   matchid           251456 non-null  int64
 1   inning            251456 non-null  int64
 2   over              251456 non-null  int64
 3   ball              251456 non-null  int64
 4   batting_team      251456 non-null  object
 5   bowling_team      251456 non-null  object
 6   batsman           251456 non-null  object
 7   non_striker       251456 non-null  object
 8   bowler            251456 non-null  object
 9   batsman_runs      251456 non-null  int64
 10  extras            251456 non-null  int64
 11  iswide            251456 non-null  float64
 12  isnoball          251456 non-null  float64
 13  byes              251456 non-null  float64
 14  legbyes           251456 non-null  float64
 15  penalty           251456 non-null  float64
 16  dismissal_kind    251456 non-null  object
 17  player_dismissed  251456 non-null  object
 18  date              251456 non-null  object
 19  total_runs        251456 non-null  float64
 20  is_wicket         251456 non-null  int64
dtypes: float64(6), int64(7), object(8)
memory usage: 42.2+ MB

,matchid,inning,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,...,iswide,isnoball,byes,legbyes,penalty,dismissal_kind,player_dismissed,date,total_runs,is_wicket
0,335982,1,0,1,kolkata knight riders,royal challengers bangalore,sc ganguly,bb mccullum,p kumar,0,...,0.0,0.0,0.0,1.0,0.0,none,none,2008-04-18,2.0,0
1,335982,1,0,2,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,0.0,0
2,335982,1,0,3,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,1.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,1.0,0
3,335982,1,0,4,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,0.0,0
4,335982,1,0,5,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,0.0,0

In [30]:
# Converting date column to datetime
df["date"] = pd.to_datetime(df["date"], errors="coerce")

# Removing rows with invalid dates
df = df[df["date"].notna()]

# Casting integer columns explicitly
int_cols = [
    "matchid", "inning", "over", "ball",
    "batsman_runs", "extras",
    "total_runs", "is_wicket"
]

df[int_cols] = df[int_cols].astype(int)
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 251456 entries, 0 to 260919
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   matchid           251456 non-null  int64
 1   inning            251456 non-null  int64
 2   over              251456 non-null  int64
 3   ball              251456 non-null  int64
 4   batting_team      251456 non-null  object
 5   bowling_team      251456 non-null  object
 6   batsman           251456 non-null  object
 7   non_striker       251456 non-null  object
 8   bowler            251456 non-null  object
 9   batsman_runs      251456 non-null  int64
 10  extras            251456 non-null  int64
 11  iswide            251456 non-null  float64
 12  isnoball          251456 non-null  float64
 13  byes              251456 non-null  float64
 14  legbyes           251456 non-null  float64
 15  penalty           251456 non-null  float64
 16  dismissal_kind    251456 non-null  object
 17  player_dismissed  251456 non-null  object
 18  date              251456 non-null  datetime64[ns]
 19  total_runs        251456 non-null  int64
 20  is_wicket         251456 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(8), object(7)
memory usage: 42.2+ MB

,matchid,inning,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,...,iswide,isnoball,byes,legbyes,penalty,dismissal_kind,player_dismissed,date,total_runs,is_wicket
0,335982,1,0,1,kolkata knight riders,royal challengers bangalore,sc ganguly,bb mccullum,p kumar,0,...,0.0,0.0,0.0,1.0,0.0,none,none,2008-04-18,2,0
1,335982,1,0,2,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,0,0
2,335982,1,0,3,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,1.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,1,0
3,335982,1,0,4,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,0,0
4,335982,1,0,5,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,0,0

In [31]:
# Sorting dataset chronologically for time-series safety
df = df.sort_values(
    by=["date", "matchid", "inning", "over", "ball"]
).reset_index(drop=True)

# Saving the cleaned dataset
df.to_csv("data/deliveries_cleaned.csv", index=False)

print("Section 5.1 data cleaning completed successfully.")
df.info()
df.head()

Section 5.1 data cleaning completed successfully.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251456 entries, 0 to 251455
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   matchid           251456 non-null  int64
 1   inning            251456 non-null  int64
 2   over              251456 non-null  int64
 3   ball              251456 non-null  int64
 4   batting_team      251456 non-null  object
 5   bowling_team      251456 non-null  object
 6   batsman           251456 non-null  object
 7   non_striker       251456 non-null  object
 8   bowler            251456 non-null  object
 9   batsman_runs      251456 non-null  int64
 10  extras            251456 non-null  int64
 11  iswide            251456 non-null  float64
 12  isnoball          251456 non-null  float64
 13  byes              251456 non-null  float64
 14  legbyes           251456 non-null  float64
 15  penalty           251456 non-null  float64
 16  dismissal_kind    251456 non-null  object
 17  player_dismissed  251456 non-null  object
 18  date              251456 non-null  datetime64[ns]
 19  total_runs        251456 non-null  int64
 20  is_wicket         251456 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(8), object(7)
memory usage: 40.3+ MB

,matchid,inning,over,ball,batting_team,bowling_team,batsman,non_striker,bowler,batsman_runs,...,iswide,isnoball,byes,legbyes,penalty,dismissal_kind,player_dismissed,date,total_runs,is_wicket
0,335982,1,0,1,kolkata knight riders,royal challengers bangalore,sc ganguly,bb mccullum,p kumar,0,...,0.0,0.0,0.0,1.0,0.0,none,none,2008-04-18,2,0
1,335982,1,0,2,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,0,0
2,335982,1,0,3,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,1.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,1,0
3,335982,1,0,4,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,0,0
4,335982,1,0,5,kolkata knight riders,royal challengers bangalore,bb mccullum,sc ganguly,p kumar,0,...,0.0,0.0,0.0,0.0,0.0,none,none,2008-04-18,0,0