In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
ball = pd.read_csv("c:/Users/Danish/OneDrive/Desktop/infosys/Datasets/ball_by_ball_data.csv")
matches = pd.read_csv("c:/Users/Danish/OneDrive/Desktop/infosys/Datasets/ipl_matches_data.csv")
players = pd.read_csv("c:/Users/Danish/OneDrive/Desktop/infosys/Datasets/players-data-updated.csv")
team_alias = pd.read_csv("c:/Users/Danish/OneDrive/Desktop/infosys/Datasets/team_aliases.csv")
teams_data = pd.read_csv("c:/Users/Danish/OneDrive/Desktop/infosys/Datasets/teams_data.csv")

In [27]:
ball.head()

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,is_bye,is_penalty,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,6,1,0,0,0,...,False,False,0,0,1,0,0,NaN,False,1
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,1,0,...,False,False,0,0,0,0,0,NaN,False,1
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,2,0,...,False,False,1,0,0,0,0,NaN,False,1
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,3,0,...,False,False,0,0,0,0,0,NaN,False,1
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,4,0,...,False,False,0,0,0,0,0,NaN,False,1

In [28]:
matches.head()

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,venue,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,M Chinnaswamy Stadium,1,1,6,field,6,140.0,NaN,46.0,win
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,"Rajiv Gandhi International Stadium, Uppal",1,2,1,field,2,35.0,NaN,15.0,win
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Maharashtra Cricket Association Stadium,4,4,3,field,4,NaN,7.0,36.0,win
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Saurashtra Cricket Association Stadium,6,5,6,field,6,NaN,10.0,57.0,win
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Holkar Cricket Stadium,494,494,4,field,494,NaN,6.0,71.0,win

In [29]:
ball.shape

(278205, 30)

In [30]:
matches.shape

(1169, 23)

In [31]:
players.shape

(772, 6)

In [32]:
team_alias.shape

(46, 3)

In [33]:
teams_data.shape

(16, 2)

In [34]:
ball.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 30 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   season_id          278205 non-null  int64
 1   match_id           278205 non-null  int64
 2   batter             278205 non-null  object
 3   bowler             278205 non-null  object
 4   non_striker        278205 non-null  object
 5   team_batting       278205 non-null  int64
 6   team_bowling       278205 non-null  int64
 7   over_number        278205 non-null  int64
 8   ball_number        278205 non-null  int64
 9   batter_runs        278205 non-null  int64
 10  extras             278205 non-null  int64
 11  total_runs         278205 non-null  int64
 12  batsman_type       278205 non-null  object
 13  bowler_type        278205 non-null  object
 14  player_out         13823 non-null   object
 15  fielders_involved  13823 non-null   object
 16  is_wicket          278205 non-null  bool
 17  is_wide_ball       278205 non-null  bool
 18  is_no_ball         278205 non-null  bool
 19  is_leg_bye         278205 non-null  bool
 20  is_bye             278205 non-null  bool
 21  is_penalty         278205 non-null  bool
 22  wide_ball_runs     278205 non-null  int64
 23  no_ball_runs       278205 non-null  int64
 24  leg_bye_runs       278205 non-null  int64
 25  bye_runs           278205 non-null  int64
 26  penalty_runs       278205 non-null  int64
 27  wicket_kind        13823 non-null   object
 28  is_super_over      278205 non-null  bool
 29  innings            278205 non-null  int64
dtypes: bool(7), int64(15), object(8)
memory usage: 50.7+ MB

In [35]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_id         1169 non-null   int64
 1   season_id        1169 non-null   int64
 2   balls_per_over   1169 non-null   int64
 3   city             1118 non-null   object
 4   match_date       1169 non-null   object
 5   event_name       1169 non-null   object
 6   match_number     1099 non-null   float64
 7   gender           1169 non-null   object
 8   match_type       1169 non-null   object
 9   format           1169 non-null   object
 10  overs            1169 non-null   int64
 11  season           1169 non-null   object
 12  team_type        1169 non-null   object
 13  venue            1169 non-null   object
 14  toss_winner      1169 non-null   int64
 15  team1            1169 non-null   int64
 16  team2            1169 non-null   int64
 17  toss_decision    1169 non-null   object
 18  match_winner     1169 non-null   int64
 19  win_by_runs      531 non-null    float64
 20  win_by_wickets   615 non-null    float64
 21  player_of_match  1161 non-null   float64
 22  result           1169 non-null   object
dtypes: float64(4), int64(8), object(11)
memory usage: 210.2+ KB

In [36]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 772 entries, 0 to 771
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         772 non-null    int64
 1   player_name       772 non-null    object
 2   bat_style         772 non-null    object
 3   bowl_style        759 non-null    object
 4   field_pos         707 non-null    object
 5   player_full_name  772 non-null    object
dtypes: int64(1), object(5)
memory usage: 36.3+ KB

In [37]:
team_alias.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   alias_id    46 non-null     int64
 1   team_id     46 non-null     int64
 2   alias_name  46 non-null     object
dtypes: int64(2), object(1)
memory usage: 1.2+ KB

In [38]:
teams_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   team_id    16 non-null     int64
 1   team_name  16 non-null     object
dtypes: int64(1), object(1)
memory usage: 388.0+ bytes

In [39]:
team_alias.head(), teams_data.head()

(   alias_id  team_id                   alias_name
 0         1        1                          RCB
 1         2        1  Royal Challengers Bengaluru
 2         3      252             Delhi Daredevils
 3         4      494              Kings XI Punjab
 4         5        1  Royal Challengers Bangalore,
    team_id                    team_name
 0        1  Royal Challengers Bangalore
 1        2          Sunrisers Hyderabad
 2        3               Mumbai Indians
 3        4       Rising Pune Supergiant
 4        5                Gujarat Lions)

# *Cheching Duplicates*

In [40]:
def check_duplicates(df, name):
    dup_count = df.duplicated().sum()
    if dup_count == 0:
        print(f" {name}: No duplicate rows found")
    else:
        print(f" {name}: {dup_count} duplicate rows found")
    return dup_count

In [41]:
check_duplicates(ball, "Ball-by-Ball Data")
check_duplicates(matches, "Matches Data")
check_duplicates(players, "Players Data")
check_duplicates(team_alias, "Team Aliases Data")
check_duplicates(teams_data, "Teams Data")

 Ball-by-Ball Data: No duplicate rows found
 Matches Data: No duplicate rows found
 Players Data: No duplicate rows found
 Team Aliases Data: No duplicate rows found
 Teams Data: No duplicate rows found

np.int64(0)

In [42]:
team_alias['alias_name'].value_counts()

alias_name
RCB                            1
Royal Challengers Bengaluru    1
Delhi Daredevils               1
Kings XI Punjab                1
Royal Challengers Bangalore    1
Banglore                       1
Bengaluru                      1
Delhi Capitals                 1
DC                             1
DD                             1
Delhi                          1
Punjab Kings                   1
KXIP                           1
Punjab                         1
Sunrisers Hyderabad            1
SRH                            1
Hyderabad                      1
Deccan Chargers                1
Mumbai Indians                 1
MI                             1
Mumbai                         1
Rising Pune Supergiant         1
Rising Pune Supergiants        1
RPS                            1
Pune                           1
Gujarat Lions                  1
GL                             1
Kolkata Knight Riders          1
KKR                            1
Kolkatta                       1
Chennai Super Kings            1
CSK                            1
Chennai                        1
Rajasthan Royals               1
Rajasthan                      1
RR                             1
Lucknow Super Giants           1
LSG                            1
Lucknow                        1
Gujarat Titans                 1
GT                             1
Kochi Tuskers Kerala           1
KTK                            1
Kerala                         1
Pune Warriors                  1
PWI                            1
Name: count, dtype: int64

In [43]:
team_alias['alias_name'] = team_alias['alias_name'].replace({
    'RCB': 'Royal Challengers Bengaluru',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Banglore': 'Royal Challengers Bengaluru',
    'Bengaluru': 'Royal Challengers Bengaluru', 
    # Delhi
    'Delhi Daredevils': 'Delhi Capitals',
    'Delhi Capitals': 'Delhi Capitals',
    'DC': 'Delhi Capitals',
    'DD': 'Delhi Capitals',
    'Delhi': 'Delhi Capitals',

    # Punjab kings
    'Kings XI Punjab': 'Punjab Kings',
    'Punjab Kings': 'Punjab Kings',
    'KXIP': 'Punjab Kings',
    'Punjab': 'Punjab Kings',

    # Sunrisers Hyderabad
    'Sunrisers Hyderabad': 'Sunrisers Hyderabad',
    'SRH': 'Sunrisers Hyderabad',
    'Hyderabad': 'Sunrisers Hyderabad',
    'Deccan Chargers': 'Sunrisers Hyderabad',

    # Mumbai Indians
    'Mumbai Indians': 'Mumbai Indians',
    'MI': 'Mumbai Indians',
    'Mumbai': 'Mumbai Indians',

    # Rising Pune Supergiants
    'Rising Pune Supergiant': 'Rising Pune Supergiants',
    'Rising Pune Supergiants': 'Rising Pune Supergiants',
    'RPS': 'Rising Pune Supergiants',
    'Pune': 'Rising Pune Supergiants',
    
    # Gujarat Lions
    'Gujarat Lions': 'Gujarat Lions',
    'GL': 'Gujarat Lions',

    # Kolkata Knight Riders
    'Kolkata Knight Riders': 'Kolkata Knight Riders',
    'KKR': 'Kolkata Knight Riders',
    'Kolkatta': 'Kolkata Knight Riders',

    # Chennai Super Kings
    'Chennai Super Kings': 'Chennai Super Kings',
    'CSK': 'Chennai Super Kings',
    'Chennai': 'Chennai Super Kings',

    # Rajasthan Royals
    'Rajasthan Royals': 'Rajasthan Royals',
    'RR': 'Rajasthan Royals',
    'Rajasthan': 'Rajasthan Royals',

    # Lucknow Super Giants
    'Lucknow Super Giants': 'Lucknow Super Giants',
    'LSG': 'Lucknow Super Giants',
    'Lucknow': 'Lucknow Super Giants',

    # Gujarat Titans
    'Gujarat Titans': 'Gujarat Titans',
    'GT': 'Gujarat Titans',

    # Kochi Tuskers Kerala
    'Kochi Tuskers Kerala': 'Kochi Tuskers Kerala',
    'KTK': 'Kochi Tuskers Kerala',
    'Kerala': 'Kochi Tuskers Kerala',

    # Pune Warriors India
    'Pune Warriors': 'Pune Warriors India',
    'PWI': 'Pune Warriors India'
})

In [44]:
team_alias['alias_name'].value_counts()

alias_name
Royal Challengers Bengaluru    5
Delhi Capitals                 5
Punjab Kings                   4
Sunrisers Hyderabad            4
Rising Pune Supergiants        4
Mumbai Indians                 3
Kolkata Knight Riders          3
Chennai Super Kings            3
Rajasthan Royals               3
Lucknow Super Giants           3
Kochi Tuskers Kerala           3
Gujarat Lions                  2
Gujarat Titans                 2
Pune Warriors India            2
Name: count, dtype: int64

## # *DATA STANDARDIZATION*

In [45]:
team_id_map = dict(zip(teams_data['team_id'], teams_data['team_name']))

In [46]:
team_alias_map = dict(zip(team_alias['team_id'], team_alias['alias_name']))

In [50]:
def map_team_name(value):

    if value in team_id_map:
        return team_id_map[value]

    if value in team_alias_map:
        return team_alias_map[value]
    
    return value

In [53]:
team_columns_matches = ['team1', 'team2', 'toss_winner', 'match_winner']

for col in team_columns_matches:
    if col in matches.columns:
        matches[col] = matches[col].apply(map_team_name)

In [61]:
team_columns_ball = ['team_batting', 'team_bowling']

for col in team_columns_ball:
    if col in ball.columns:
        ball[col] = ball[col].apply(map_team_name)

In [62]:
matches['team1'].unique()

array(['Royal Challengers Bangalore', 'Sunrisers Hyderabad',
       'Rising Pune Supergiant', 'Gujarat Lions', 'Punjab Kings',
       'Mumbai Indians', 'Kolkata Knight Riders', 'Delhi Capitals',
       'Rajasthan Royals', 'Chennai Super Kings', 'Lucknow Super Giants',
       'Gujarat Titans', 'Kochi Tuskers Kerala', 'Pune Warriors'],
      dtype=object)

In [63]:
matches[['team1', 'team2', 'toss_winner', 'match_winner']].dtypes

team1           object
team2           object
toss_winner     object
match_winner    object
dtype: object

In [64]:
ball[['team_batting', 'team_bowling']].dtypes

team_batting    object
team_bowling    object
dtype: object

In [100]:
matches.head()

,match_id,season_id,city,match_date,match_number,match_type,overs,venue,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result
0,335982,2008,Bangalore,2008-04-18,1.0,T20,20,M Chinnaswamy Stadium,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,140.0,0.0,BB McCullum,win
1,1082591,2017,Hyderabad,2017-04-05,1.0,T20,20,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35.0,0.0,Yuvraj Singh,win
2,1082592,2017,Pune,2017-04-06,2.0,T20,20,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,Rising Pune Supergiant,Mumbai Indians,field,Rising Pune Supergiant,0.0,7.0,SPD Smith,win
3,1082593,2017,Rajkot,2017-04-07,3.0,T20,20,Saurashtra Cricket Association Stadium,Kolkata Knight Riders,Gujarat Lions,Kolkata Knight Riders,field,Kolkata Knight Riders,0.0,10.0,CA Lynn,win
4,1082594,2017,Indore,2017-04-08,4.0,T20,20,Holkar Cricket Stadium,Punjab Kings,Punjab Kings,Rising Pune Supergiant,field,Punjab Kings,0.0,6.0,GJ Maxwell,win

# ID to Player Name

In [101]:
player_id_to_name = dict(
    zip(players['player_id'], players['player_name'])
)

In [102]:
def map_player_of_match(value):
    # Missing value
    if pd.isna(value):
        return "Not Awarded"
    
    #  ID exists in players table
    if value in player_id_to_name:
        return player_id_to_name[value]
    
    return value

In [103]:
matches['player_of_match'] = matches['player_of_match'].apply(map_player_of_match)

In [104]:
# No numbers should remain
matches['player_of_match'].apply(
    lambda x: isinstance(x, (int, float))
).sum()

np.int64(0)

In [105]:
matches['player_of_match'].value_counts().head(10)

player_of_match
AB de Villiers    25
CH Gayle          22
RG Sharma         21
V Kohli           19
MS Dhoni          18
DA Warner         18
SP Narine         17
AD Russell        16
YK Pathan         16
RA Jadeja         16
Name: count, dtype: int64

# Imputation

In [106]:
def null_report(df, name):
    
    print(f"\n===== {name} =====")
    total_rows = df.shape[0]
    
    null_count = df.isnull().sum()
    null_percent = (null_count / total_rows) * 100
    
    report = pd.DataFrame({
        "Null_Count": null_count,
        "Null_Percent": null_percent
    }).sort_values(by="Null_Percent", ascending=False)
    
    report = report[report["Null_Count"] > 0]
    
    if report.empty:
        print("No null values found ")
    else:
        print(report)

In [107]:
null_report(ball, "Ball By Ball Data")
null_report(matches, "Matches Data")

===== Ball By Ball Data =====
No null values found

===== Matches Data =====
No null values found

In [108]:
ball['wicket_kind'] = ball['wicket_kind'].fillna('No Wicket')
ball['player_out'] = ball['player_out'].fillna('Not Out')
ball['fielders_involved'] = ball['fielders_involved'].fillna('None')

In [109]:
matches['win_by_runs'] = matches['win_by_runs'].fillna(0)
matches['win_by_wickets'] = matches['win_by_wickets'].fillna(0)

In [110]:
matches['city'] = matches['city'].fillna('Not Recorded')
matches['match_number'] = matches['match_number'].fillna('Unknown Match')

In [111]:
null_report(ball, "Ball By Ball")
null_report(matches, "Matches")

===== Ball By Ball =====
No null values found

===== Matches =====
No null values found

In [112]:
null_report(players, "Players Data")
null_report(team_alias, "Team Aliases")
null_report(teams_data, "Teams Data")

===== Players Data =====
No null values found

===== Team Aliases =====
No null values found

===== Teams Data =====
No null values found

In [113]:
players['bowl_style'] = players['bowl_style'].fillna('Not a Bowler')
players['field_pos'] = players['field_pos'].fillna('Not Specified')

In [114]:
null_report(players, "Players Data")

===== Players Data =====
No null values found

In [115]:
ball.isnull().sum()

season_id            0
match_id             0
batter               0
bowler               0
non_striker          0
team_batting         0
team_bowling         0
over_number          0
ball_number          0
batter_runs          0
extras               0
total_runs           0
batsman_type         0
bowler_type          0
player_out           0
fielders_involved    0
is_wicket            0
is_wide_ball         0
is_no_ball           0
is_leg_bye           0
is_bye               0
is_penalty           0
wide_ball_runs       0
no_ball_runs         0
leg_bye_runs         0
bye_runs             0
penalty_runs         0
wicket_kind          0
is_super_over        0
innings              0
dtype: int64

In [116]:
matches.isnull().sum()

match_id           0
season_id          0
city               0
match_date         0
match_number       0
match_type         0
overs              0
venue              0
toss_winner        0
team1              0
team2              0
toss_decision      0
match_winner       0
win_by_runs        0
win_by_wickets     0
player_of_match    0
result             0
dtype: int64

# Removing unwanted columns

In [117]:
matches_drop_cols = [
    'balls_per_over',
    'gender',
    'team_type',
    'format',
    'event_name',
    'season'
]

matches.drop(columns=matches_drop_cols, inplace=True, errors='ignore')

In [118]:
matches.shape

(1169, 17)

# Outliers

In [119]:
def outlier_stats_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[column] < lower) | (df[column] > upper)]

    total_rows = df.shape[0]
    outlier_count = outliers.shape[0]
    outlier_percent = (outlier_count / total_rows) * 100

    return outlier_count, outlier_percent

In [120]:
count, percent = outlier_stats_iqr(ball, "batter_runs")

print("Outliers in total_runs:", count)
print("Outlier percentage:", round(percent, 2), "%")

Outliers in total_runs: 47344
Outlier percentage: 17.02 %

In [121]:
numeric_cols_ball = [
    "batter_runs",
    "extras",
    "total_runs",
    "wide_ball_runs",
    "no_ball_runs",
    "leg_bye_runs",
    "bye_runs"
]

outlier_report = []

for col in numeric_cols_ball:
    count, percent = outlier_stats_iqr(ball, col)
    outlier_report.append([col, count, round(percent, 2)])

outlier_df = pd.DataFrame(
    outlier_report,
    columns=["Column", "Outlier_Count", "Outlier_Percentage"]
)

outlier_df

           Column  Outlier_Count  Outlier_Percentage
0     batter_runs          47344               17.02
1          extras          15133                5.44
2      total_runs          48367               17.39
3  wide_ball_runs           9080                3.26
4    no_ball_runs           1163                0.42
5    leg_bye_runs           4215                1.52
6        bye_runs            701                0.25

In [122]:
matches.head()

,match_id,season_id,city,match_date,match_number,match_type,overs,venue,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result
0,335982,2008,Bangalore,2008-04-18,1.0,T20,20,M Chinnaswamy Stadium,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,140.0,0.0,BB McCullum,win
1,1082591,2017,Hyderabad,2017-04-05,1.0,T20,20,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35.0,0.0,Yuvraj Singh,win
2,1082592,2017,Pune,2017-04-06,2.0,T20,20,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,Rising Pune Supergiant,Mumbai Indians,field,Rising Pune Supergiant,0.0,7.0,SPD Smith,win
3,1082593,2017,Rajkot,2017-04-07,3.0,T20,20,Saurashtra Cricket Association Stadium,Kolkata Knight Riders,Gujarat Lions,Kolkata Knight Riders,field,Kolkata Knight Riders,0.0,10.0,CA Lynn,win
4,1082594,2017,Indore,2017-04-08,4.0,T20,20,Holkar Cricket Stadium,Punjab Kings,Punjab Kings,Rising Pune Supergiant,field,Punjab Kings,0.0,6.0,GJ Maxwell,win

In [124]:
matches_drop_cols = [
    'match_type'
]

matches.drop(columns=matches_drop_cols, inplace=True, errors='ignore')

In [126]:
matches.head()

,match_id,season_id,city,match_date,match_number,overs,venue,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result
0,335982,2008,Bangalore,2008-04-18,1.0,20,M Chinnaswamy Stadium,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,140.0,0.0,BB McCullum,win
1,1082591,2017,Hyderabad,2017-04-05,1.0,20,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Sunrisers Hyderabad,35.0,0.0,Yuvraj Singh,win
2,1082592,2017,Pune,2017-04-06,2.0,20,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,Rising Pune Supergiant,Mumbai Indians,field,Rising Pune Supergiant,0.0,7.0,SPD Smith,win
3,1082593,2017,Rajkot,2017-04-07,3.0,20,Saurashtra Cricket Association Stadium,Kolkata Knight Riders,Gujarat Lions,Kolkata Knight Riders,field,Kolkata Knight Riders,0.0,10.0,CA Lynn,win
4,1082594,2017,Indore,2017-04-08,4.0,20,Holkar Cricket Stadium,Punjab Kings,Punjab Kings,Rising Pune Supergiant,field,Punjab Kings,0.0,6.0,GJ Maxwell,win

In [127]:
ball.head()

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,is_bye,is_penalty,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,Kolkata Knight Riders,Royal Challengers Bangalore,0,0,0,...,False,False,0,0,1,0,0,No Wicket,False,1
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0,...,False,False,0,0,0,0,0,No Wicket,False,1
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,...,False,False,1,0,0,0,0,No Wicket,False,1
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0,...,False,False,0,0,0,0,0,No Wicket,False,1
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,...,False,False,0,0,0,0,0,No Wicket,False,1

In [137]:
import os

cleaned_path = "c:/Users/Danish/OneDrive/Desktop/infosys/Datasets/Cleaned_Datasets"
os.makedirs(cleaned_path, exist_ok=True)

In [ ]:
cleaned_path = "Datasets/Cleaned_Datasets"

ball.to_csv(f"{cleaned_path}/ball_cleaned_data.csv", index=False)
matches.to_csv(f"{cleaned_path}/matches_cleaned_data.csv", index=False)
players.to_csv(f"{cleaned_path}/players_cleaned_data.csv", index=False)
team_alias.to_csv(f"{cleaned_path}/team_aliases_cleaned_data.csv", index=False)
teams_data.to_csv(f"{cleaned_path}/teams_data_cleaned_data.csv", index=False)